tun:
  mock: ${TUN_MOCK}
  address: ${VPN_NET}
  mask-length: ${VPN_NET_LENGTH}

vpn:
  server:
    host: ${SERVER_HOST}
    port: ${SERVER_PORT}

logging:
  level:
    com:
      stevesad: ${LOGGING_LEVEL}