spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

tun:
  mock: ${TUN_MOCK}
  address: ${VPN_NET}
  mask-length: ${VPN_NET_LENGTH}

vpn:
  server:
    host: ${SERVER_HOST}
    port: ${SERVER_PORT}

logging:
  level:
    com:
      stevesad: ${LOGGING_LEVEL}