services:
  postgres:
    image: postgres:17-bookworm
    environment:
      POSTGRES_DB: java_vpn_server
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: