tun:
  mock: none
  address: 10.2.1.7

vpn:
  server:
    remote-address: 185.10.19.139
    remote-port: 18083
  client:
    certificate-path: /Users/andrey/java-vpn/certs/client_cert.pem
    private-key-path: /Users/andrey/java-vpn/certs/client_key.pem

logging:
  level:
    com:
      stevesad: DEBUG
#    io:
#      netty:
#        handler:
#          ssl: DEBUG
#    reactor:
#      netty:
#        quic: DEBUG