tun:
  mock: ping
  address: 10.2.1.7

vpn:
  server:
    remote-address: 127.0.0.1
    remote-port: 8083
  client:
    certificate-path: /Users/andrey/java-vpn/certs/client_cert.pem
    private-key-path: /Users/andrey/java-vpn/certs/client_key.pem


logging:
  level:
    com:
      stevesad: DEBUG